alertmanager:
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - alertmanager.ampeleelectricals.com
    paths:
    - /
    pathType: Prefix  
    tls:
    - secretName: dev-alertmanager
      hosts:
      - alertmanager.ampeleelectricals.com
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi
grafana:
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - grafana.ampeleelectricals.com
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: dev-grafana
      hosts:
      - grafana.ampeleelectricals.com
  sidecar:
    datasources:
      url: http://kube-promethues-stack-kube-prometheus.monitoring.svc.cluster.local:9090
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-stack.monitoring.svc.cluster.local:3100
      jsonData:
        maxLines: 1000

prometheus:
  ingress:
    ingressClassName: nginx
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
    - prometheus.ampeleelectricals.com
    paths:
    - /
    pathType: Prefix
    tls:
    - secretName: dev-prometheus
      hosts:
      - prometheus.ampeleelectricals.com
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-client
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi