apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.fullname" . }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
