apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: NxhpJkjViXBVoN1aIFFT0xLHcZc9gabsfr2fpWkP

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: NxhpJkjViXBVoN1aIFFT0xLHcZc9gabsfr2fpWkP
