apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: dvE8_m6D8zCE0RQFY0LIr-krHAahrwkOtKRI2GDh

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: dvE8_m6D8zCE0RQFY0LIr-krHAahrwkOtKRI2GDh
