---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: production-certificate
spec:
  secretName: production-domain-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  duration: 2160h                  # Valid for 90 Days
  renewBefore: 720h                # 30d before SSL will expire, renew it
  dnsNames:
    - "*.ampeleelectricals.com"